AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Lambda function for login APIM

Resources:
  IcApimLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 1024
      Timeout: 10
      Environment:
        Variables:
          ENV: dev
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /list/services
            Method: GET
