AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Lambda function for login APIM

Resources:
  IcApimLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Environment:
        Variables:
          USER_POOL_ID: us-east-1_SqRB9UaHj
          CLIENT_ID: 454qelaoerh3efnhi356a3n04f
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/login
            Method: GET
        EndpointRefresh:
          Type: Api
          Properties:
            Path: /auth/refresh
            Method: GET
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:InitiateAuth
              Resource: "*"
